sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"

before_script:
  - npm install -g nsp
  - git config --global user.name 'Travis-CI'
  - git config --global user.email 'dummy@example.org'

script: nsp check

after_script: NODE_ENV=test istanbul cover -x test.js ./node_modules/mocha/bin/_mocha -- -R spec --timeout 30000 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  email:
    on_success: never
    on_failure: always




